language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"

branches:
  only:
    - master
    - development

install:
  - travis_retry pip install -r requirements.txt "jinja2>=2.7" msgpack-python pyyaml
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then travis_retry pip install pint coveralls ply; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then nosetests --all-modules --with-coverage --cover-package odin tests/ ; fi
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then nosetests --all-modules --with-coverage --cover-package odin tests/ tests/contrib ; fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then coveralls; fi
