language: python

python:
  - "2.7"
  - "3.3"

branches:
  only:
    - master
    #- development

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install -r requirements-optional.txt --use-mirrors
  - pip install coveralls --use-mirrors

script: nosetests --all-modules --with-coverage --cover-package odin tests/

after_success:
  - coveralls
