language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

branches:
  only:
    - master
    #- development

install:
  - pip install -r requirements.txt --use-mirrors
  - pip install "jinja2>=2.7" --use-mirrors
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install pint --use-mirrors
  - pip install coveralls --use-mirrors

script: nosetests --all-modules --with-coverage --cover-package odin tests/

after_success:
  - coveralls
